graem:setup({
    import={
        "net.eduvax.graem"
    },
    components={
        Sky={
            class="SkyBox",
        },
        Light={
            class="DefaultLight",
            shadowmapSize=4096
        },
        Playfield={ class="Playfield" },
        ["Mobile Object Trajectory"]={
            class="Trajectory",
            bind={
                time="time",
                location="world.body.loc",
            },
            changeOfBasis={
                class="BasisLLAtoJMErel"
            }
        },
        ["Mobile Object"]={
            class="DummyAvatar",
            bind={
                time="time",
                location="world.body.loc",
                attitude="world.body.q",
                split="split"
            },
            changeOfBasis={
                class="BasisLLAtoJMErel"
            }
        },
        cam={
            class="AutoChaseCam",
        }
    },
})
